Re-enable debug mode, add sleep until process has ended before attempting to restart

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -26,17 +26,19 @@ mix deps.get
 mix release --overwrite
 
 # Stop any existing instances of the app
-echo "> Stopping existing instances of the app"
-if [[ -n "$($APP pid)" ]]; then
-  $APP stop
-fi
+echo "> Stopping running instances of the app"
+$APP stop || true
+
+while [[ -n "$($APP pid)" ]]; do
+    echo "  > Waiting for app to stop"
+done
 
 # ------------------------------------------------------------------------------
 # DEBUGGING
 # ------------------------------------------------------------------------------
 if [[ -n "${DEBUG:-}" ]]; then
     echo "> DEBUG MODE ENABLED"
-    echo "> Starting app in foreground"
+    echo "  > Starting app in foreground"
 
     # Start our app in the foreground and log output
     $APP start > app.log 2>&1 &
@@ -49,8 +51,8 @@ if [[ -n "${DEBUG:-}" ]]; then
 
     # Check the log for errors
     if grep -q "error" app.log; then
-      echo "Errors found during start. Check app.log for details."
-      exit 1
+        echo "  > Errors found during start. Check app.log for details."
+        exit 1
     fi
 fi
 
@@ -65,9 +67,9 @@ sleep 5
 # Check if the app is running
 echo "> Checking if app is running"
 if [[ -z "$($APP pid)" ]]; then
-  echo "Application failed to start"
-  exit 1
+    echo "  > Application failed to start"
+    exit 1
+else
+    echo "  > App started successfully"
+    exit 0
 fi
-
-echo "> App started successfully"
-exit 0
