comment out debugging steps, remove -x and add some echoes instead

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -1,54 +1,66 @@
 #!/usr/bin/env bash
 
-set -eux -o pipefail
+set -eu -o pipefail
 
 export MIX_ENV=prod
 export APP="_build/prod/rel/words_etc/bin/words_etc"
 
 # Ensure our database path exists
+echo "> Ensuring database path exists"
 sudo mkdir -p "$(dirname "$DATABASE_PATH")"
 sudo chown -Rf sysread "$(dirname "$DATABASE_PATH")"
 
 # Install dependencies
+echo "> Installing dependencies"
 sudo apt install -y libssl-dev automake autoconf libncurses5-dev
 
 # Install erlang and elixir with asdf
+echo "> Installing erlang and elixir using asdf"
 source "$HOME/.asdf/asdf.sh"
 asdf install
 
 # Build our app release
+echo "> Building release"
 mix local.hex --force
 mix deps.get
 mix release --overwrite
 
 # Stop any existing instances of the app
+echo "> Stopping existing instances of the app"
 if [[ -n "$($APP pid)" ]]; then
   $APP stop || true
 fi
 
+# ------------------------------------------------------------------------------
+# DEBUGGING
+# ------------------------------------------------------------------------------
 # Start our app in the foreground and log output
-$APP start > app.log 2>&1 &
+#$APP start > app.log 2>&1 &
 # Allow the application to run for a few seconds
-sleep 5
+#sleep 5
 # Then stop the application
-$APP stop || true
+#$APP stop || true
 
 # Check the log for errors
-if grep -q "error" app.log; then
-  echo "Errors found during start. Check app.log for details."
-  exit 1
-fi
+#if grep -q "error" app.log; then
+#  echo "Errors found during start. Check app.log for details."
+#  exit 1
+#fi
 
 # Now attempt to start the app as a daemon
+echo "> Starting app as daemon"
 $APP daemon
 
 # Wait for the app to start
+echo "> Waiting for app to start"
 sleep 5
 
 # Check if the app is running
+echo "> Checking if app is running"
 if [[ -z "$($APP pid)" ]]; then
   echo "Application failed to start"
   exit 1
 fi
 
+echo "> App started successfully"
 exit 0
