Enable debug mode to troubleshoot deploys

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -28,23 +28,30 @@ mix release --overwrite
 # Stop any existing instances of the app
 echo "> Stopping existing instances of the app"
 if [[ -n "$($APP pid)" ]]; then
-  $APP stop || true
+  $APP stop
 fi
 
 # ------------------------------------------------------------------------------
 # DEBUGGING
 # ------------------------------------------------------------------------------
-# Start our app in the foreground and log output
-#$APP start > app.log 2>&1 &
-# Allow the application to run for a few seconds
-#sleep 5
-# Then stop the application
-#$APP stop || true
+#if [[ -n "${DEBUG:-}" ]]; then
+    echo "> DEBUG MODE ENABLED"
+    echo "> Starting app in foreground"
 
-# Check the log for errors
-#if grep -q "error" app.log; then
-#  echo "Errors found during start. Check app.log for details."
-#  exit 1
+    # Start our app in the foreground and log output
+    $APP start > app.log 2>&1 &
+
+    # Allow the application to run for a few seconds
+    sleep 5
+
+    # Then stop the application
+    $APP stop || true
+
+    # Check the log for errors
+    if grep -q "error" app.log; then
+      echo "Errors found during start. Check app.log for details."
+      exit 1
+    fi
 #fi
 
 # Now attempt to start the app as a daemon
